### ISSUE TITLE
Brewfather endpoint

### ISSUE THREAD

**Issue by Naesstrom** [lbussy/brew-bubbles#16]
Brewfather.app has support for custom streams to attach to brews. According to the [docs](https://docs.brewfather.app/integrations/custom-stream) it expects the following json:
```
{
  "name": "YourDeviceName", // Required field, this will be the ID in Brewfather
  "temp": 20.32,
  "aux_temp": 15.61, // Fridge Temp
  "ext_temp": 6.51, // Room Temp
  "temp_unit": "C", // C, F, K
  "gravity": 1.042,
  "gravity_unit": "G", // G, P
  "pressure": 10,
  "pressure_unit": "PSI", // PSI, BAR, KPA
  "ph": 4.12,
  "bpm": 123, // Bubbles Per Minute
  "comment": "Hello World",
  "beer": "Pale Ale"
}
```
And it looks pretty similar to the one from you
```
{
    "api_key":"Brew Bubbles",
    "device_source":"Brew Bubbles",
    "name":"xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
    "bpm":99.999,
    "ambient":70.3625,
    "temp":-196.6,
    "temp_unit":"F",
    "datetime":"2019-11-16T23:59:01.123Z"
}
```
Would it be possible to make a custom stream that fits the brewfather input? I've just ordered the parts to build a couple of these and would be great to get it all into the same place!

**Comment by Naesstrom** [comment]
I just recieved information from the developer of brewfather that it's enough with "name" and "bpm" at a minimum

**Comment by lbussy** [comment]
Very sorry I did not see this ... Brewfather is being tested right now.

**Comment by Naesstrom** [comment]
yeah I saw it in the other branch, just waiting for my wemos. Is it ok to pull that branch and test?

**Comment by lbussy** [comment]
I would wait.  Well, *I* can't wait but you should. :)

I am actively testing today, so fingers crossed.  It was one of the last things I had to do to release.

**Comment by lbussy** [comment]
Merged to devel.

While it will probably work fine right now if you wanted to test, I am not done with all of my testing and I know I have at least one bug (#19) but with luck (I hate even saying this) I should have this at least to a Release Candidate by the end of the day today.

**Comment by lbussy** [comment]
Confirmed fixed.  Working on cleaning up the release, with any luck I should be dropping a new major version here in an hour or so.

Keep in mind this will be a major version update, the configuration will be nuked.  That's the part I need to confirm actually, testing to see what happens if someone passively upgrades.

Closing as complete - stay tuned to the release notices.
