### ISSUE TITLE
Reset WiFi button not working

### ISSUE THREAD

**Issue by thomasjec** [lbussy/brew-bubbles#19]
When I try to start the Brew Bubbles controller with the reset wifi button pushed down, I get these errors (the button is connected to D5 and Gnd): 
`load 0x4010f000, len 1384, room 16 
tail 8
chksum 0x2d
csum 0x2d
v8b899c12
~ld
1970-01-01T00:00:03ZN: Serial logging started at 74880.
1970-01-01T00:00:03ZN: Fatal exception 28(LoadProhibitedCause):
epc1=0x4022dd54, epc2=0x00000000, epc3=0x00000000, excvaddr=0x0000000c, depc=0x00000000

Exception (28):
epc1=0x4022dd54 epc2=0x00000000 epc3=0x00000000 excvaddr=0x0000000c depc=0x00000000

>>>stack>>>

ctx: cont
sp: 3ffffd20 end: 3fffffc0 offset: 01a0
3ffffec0:  0000000e 00000000 3ffe8a1d 40222b32  
3ffffed0:  3fffff00 3ffef060 3fffff00 4021e744  
3ffffee0:  40261ba8 3fffff33 3ffef210 4020a468  
3ffffef0:  3fffff40 3ffef060 40261ba9 4020a702  
3fffff00:  3fffff50 3fffff40 00000010 4022abc8  
3fffff10:  5a33303a 4bc60000 3ffef060 3ffef344  
3fffff20:  40261ba8 3fffff33 3ffef060 402014e0  
3fffff30:  3fffff50 3fffff40 0000000c 0189374b  
3fffff40:  00000000 00a6fc40 00000ccd 0000000e  
3fffff50:  00000004 00000020 00000ccd 40205856  
3fffff60:  3fffdad0 00000000 3ffef060 40203e1f  
3fffff70:  feefeffe feefeffe feefeffe feefeffe  
3fffff80:  feefeffe feefeffe feefeffe feefeffe  
3fffff90:  feefeffe feefeffe feefeffe feefeffe  
3fffffa0:  3fffdad0 00000000 3ffef314 40220cfc  
3fffffb0:  feefeffe feefeffe 3ffe85a4 40100901  
<<<stack<<<
␂B��K␋␁␁��      �␌'��u�␁�^␅^�␇␗p�␀␂��I
␑\␓%␑   )d�␕␙@�Y
␑␅␂�NRA�I�T␑Z-A�
␑�␂z␆F␙��
�T�1970-01-01T00:00:03ZN: Serial logging started at 74880.
1970-01-01T00:00:03ZN: Fatal exception 28(LoadProhibitedCause):
epc1=0x4022dd54, epc2=0x00000000, epc3=0x00000000, excvaddr=0x0000000c, depc=0x00000000`

Any idea why and what might be wrong?

**Comment by lbussy** [comment]
I apologize for not seeing this sooner.  I need to figure out why my notifications are not working.

There is no reset wifi button natively on this controller.  You can add a button (or jump with wires) to D5 -> GND.  Is that what you are doing?

**Comment by thomasjec** [comment]
That is indeed what I did: connecting D5 to ground (with and without a button). Then these errors appear and the board keeps rebooting...
I was just trying this as your code checks for the resetwifi value on booting and it looked very useful.

**Comment by lbussy** [comment]
Aha!  Got you.  I see the issue, I'll work on it a little later today.

I have a more significant release pending so it will go out with that - very close though.

**Comment by lbussy** [comment]
This is confirmed fixed in devel.  I'll be releasing a major version upgrade in a little bit (definitely today).

Closing as fixed.
