### ISSUE TITLE
Room temp comes up as fridge temp in brewfather

### ISSUE THREAD

**Issue by p0ttsworth** [lbussy/brew-bubbles#36]
Not sure if this is a brewbubbles or a brewfather issue: 
I have a single temp sensor plugged into the room connector on the board, and in the brewbubbles software this correctly shows as Ambient Temp. When I send it to brewfather as a custom stream, brewfather reads that value as fridge temp, and has room temp blank.

**Comment by lbussy** [comment]
Sorry, I missed this one (I need to check my notification preferences apparently).  I'll have a look.

**Comment by lbussy** [comment]
Okay, I remember now.  This was a popular request on HBT as recorded in #24.  The link to the request on HBT is in 24 as well.

**Comment by p0ttsworth** [comment]
Fair enough, I will consider myself outvoted (unless you could "find" 11,780 votes somewhere...?)

**Comment by lbussy** [comment]
![image](https://user-images.githubusercontent.com/9092188/103652515-d671cb00-4f28-11eb-8da7-dd5ca609d4d6.png)
