### ISSUE TITLE
Brewer's Friend Logging HTTPS needed

### ISSUE THREAD

**Issue by gshadel** [lbussy/brew-bubbles#46]
It looks like Brewer's Friend has changed their logging protocol to https rather than http, according to the sample stream integration url.

    https://log.brewersfriend.com/stream/api_key_goes_here

I don't think https was available for 8266 until recently... I've seen a sample, but I didn't try out the code... I think it was focused on creating an https server rather than client however... I haven't checked out the brewbubbles logs yet... working on that next.

**Comment by lbussy** [comment]
They have always used https in their examples to my memory, but failing on an HTTP connection is new.

I'll have a look.

**Comment by gshadel** [comment]
Ok got values logged!!! All is working fine... This is a fantastic project ... I'm so excited to be able to see a graph of bubbling rates!
I changed the logging rate to 20 minutes. We'll see if the next reading makes it through... but in any case BrewBubbles is doing its part!

**Comment by gshadel** [comment]
Not failing... Just a bit slower to respond than I anticipated. Their
minimum update time was 15 min, which is what I was using. Increased mine
to 20 minutes so that might have been the issue... Or it could be I was
impatient... In any case it is capturing data now.

Thanks again for a great project. I'll be looking at the code to see how
you did all of the cool stuff my projects are missing! OTA updates, Network
setup, fantastic web screens, and the interrupt driven counting, just to
name a few.
